import { StyleSheet } from "react-native";

export const Gstyles = StyleSheet.create({
    welcome:{
        backgroundColor:'#4DFF7E',
        height:'100%',
        justifyContent:'space-around',
        alignItems:"center"
    },
    home:{
        backgroundColor:'#161616',
        paddingHorizontal:20,
        height:'100%',
        paddingTop:40,
    },
    wrapper:{
        height:'100%',
        backgroundColor:'#161616',
        paddingHorizontal:20,
    },
    text:{
        color:'#EAEAEA',
        fontWeight:300,
        fontSize:15,
        textAlign:'center',
    },
    title:{
        fontWeight:500,
        fontSize:28,
        textAlign:'center',
        color:'#FFFFFF'
    },
    wrapper2:{
        justifyContent:'space-around'
    },
    container:{
        flex:1,
    }
})